spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: hotel-api
  datasource:
    url: jdbc:postgresql://${HOST}:5442/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: hotel
security:
  jwt:
    secret_key: ${JWT_SECRET}
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days
springdoc:
  override-with-generic-response: false